Feat/list wrapper component
HuyDNA/MIPS-Simulator pull request #3
Opened 2023-03-04 17:32 UTC by phamvannhatvu

- Implement a list wrapper with common methods: move/copy constructor, pushBack(), pushFront(), popBack(), popFront(), getSize(), empty(), begin(), end(), cbegin(), cend(), operator[]

2023-03-04 17:34 UTC, HuyDNA commented on ListWrapper.h
> +    deque<T> list;
Consider using vector instead for fast random access

2023-03-04 17:36 UTC, HuyDNA requested changes
Create a new folder called WrapperClasses and place this file there

2023-03-05 13:23 UTC, HuyDNA commented on WrapperClasses/ListWrapper.h
> +    ListWrapper<T>(const ListWrapper<T> &wrapper) : list(vector<T>(wrapper.list)) {
Why the need to call vector<T>(...)?

2023-03-05 13:24 UTC, HuyDNA commented on WrapperClasses/ListWrapper.h
> +    ListWrapper<T>(ListWrapper<T> &&wrapper) noexcept : list(wrapper.list) {
Should be std::move(wrapper.list)

2023-03-05 13:24 UTC, HuyDNA requested changes
Run test for this class to ensure it works properly

2023-03-05 16:41 UTC, phamvannhatvu commented on WrapperClasses/ListWrapper.h
> +    ListWrapper<T>(const ListWrapper<T> &wrapper) : list(vector<T>(wrapper.list)) {
I thought merely list(wrapper.list) is a move assignment. I'll fix it soon!

2023-03-06 02:01 UTC, HuyDNA approved these changes

2023-03-06 02:02 UTC, merged